// DE1_SoC_QSYS_trace_system_0_link.v

// This file was auto-generated from altera_jtag_debug_link_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 13.1 182 at 2017.03.14.18:12:13

`timescale 1 ps / 1 ps
module DE1_SoC_QSYS_trace_system_0_link (
		input  wire       clk_clk,           //         clk.clk
		output wire       debug_reset_reset, // debug_reset.reset
		output wire [7:0] h2t_channel,       //         h2t.channel
		input  wire       h2t_ready,         //            .ready
		output wire       h2t_valid,         //            .valid
		output wire [7:0] h2t_data,          //            .data
		output wire       h2t_startofpacket, //            .startofpacket
		output wire       h2t_endofpacket,   //            .endofpacket
		output wire       t2h_ready,         //         t2h.ready
		input  wire       t2h_valid,         //            .valid
		input  wire [7:0] t2h_data,          //            .data
		input  wire [7:0] t2h_channel,       //            .channel
		input  wire       t2h_startofpacket, //            .startofpacket
		input  wire       t2h_endofpacket,   //            .endofpacket
		output wire       mgmt_valid,        //        mgmt.valid
		output wire [7:0] mgmt_channel,      //            .channel
		output wire       mgmt_data          //            .data
	);

	DE1_SoC_QSYS_trace_system_0_link_link link (
		.clk_clk           (clk_clk),           //         clk.clk
		.debug_reset_reset (debug_reset_reset), // debug_reset.reset
		.h2t_channel       (h2t_channel),       //         h2t.channel
		.h2t_ready         (h2t_ready),         //            .ready
		.h2t_valid         (h2t_valid),         //            .valid
		.h2t_data          (h2t_data),          //            .data
		.h2t_startofpacket (h2t_startofpacket), //            .startofpacket
		.h2t_endofpacket   (h2t_endofpacket),   //            .endofpacket
		.t2h_ready         (t2h_ready),         //         t2h.ready
		.t2h_valid         (t2h_valid),         //            .valid
		.t2h_data          (t2h_data),          //            .data
		.t2h_channel       (t2h_channel),       //            .channel
		.t2h_startofpacket (t2h_startofpacket), //            .startofpacket
		.t2h_endofpacket   (t2h_endofpacket),   //            .endofpacket
		.mgmt_valid        (mgmt_valid),        //        mgmt.valid
		.mgmt_channel      (mgmt_channel),      //            .channel
		.mgmt_data         (mgmt_data)          //            .data
	);

endmodule
